language: python
python:
  - "2.7"
  - "3.5"

services:
  - postgresql

before_script:
  - psql -c "create database test_expenses;" -U postgres

# command to install dependencies
install:
  - pip install -e expense_tracker[testing]
  - pip install coveralls
# command to run tests
script: 
  - py.test expense_tracker/expense_tracker/tests.py --cov=expense_tracker/expense_tracker --cov-report term-missing

after_success:
  - coveralls
